### PR TITLE
Add Jordan's explanation from Discourse

### PR DESCRIPTION
**Pull request by JordanMartinez**
This was copied and pasted from Discourse. Note: I didn't technically finish this guide's Cotransformer section and some of the other functions in this library weren't explained yet either.

This could likely be cleaned up a bit to remove Discourse things, but it's enough to get this going.

## What does this pull request do?

Adds the guide I wrote on Discourse: https://discourse.purescript.org/t/a-guide-to-purescript-coroutines/1258

### CODE REVIEW

**Comment by thomashoneyman** [comment]
This is great to see! As the discussion on Discourse has continued developing, I'd like to wait for that to settle so that we can merge this with the most stable version.

**Comment by thomashoneyman** [comment]
@JordanMartinez do you have any further updates you'd like to make to this? If not, I can take a pass through for typos and TODOs and then get this merged as it's a much-needed improvement over the current docs.

**Comment by JordanMartinez** [comment]
Ah... I had forgotten about this PR. Yeah, feel free to clean it up and rework it if needed.

**Comment by thomashoneyman** [comment]
I've made some updates to the text and moved the bulk of it into a dedicated docs folder (with several links and exhortations to read that documentation to understand the library).

**Pull request merged**
