### PR TITLE
Fork/join

### PR DESCRIPTION
**Pull request by paf31**
/cc @garyb @beckyconning

Is there a good place to put `Product`? `bifunctors` has bifunctor products, and `Join`. Maybe we need a `functors` library?

### CODE REVIEW

**Comment by beckyconning** [comment]
Too specific for `purescript-control`?

**Comment by paf31** [comment]
Well typically, `control` is just "control structures" which basically means classes. I think this definitely counts as a data structure, and one which is uncommon enough to be moved out into a package. `control` is used by pretty much everything.

**Comment by garyb** [comment]
We could just make a `purescript-products`? There's not much to `purescript-coproducts` either...

**Comment by paf31** [comment]
Well `Product` is just a coproduct in the dual category so maybe it should go in `coproducts` :smile: j/k

I'll put something together. I'm just wondering if a `purescript-functors` makes more sense. We have a set of `bifunctor` building blocks, so maybe a similar set of functors makes sense. `Product`, `Coproduct`, `Compose`, `Const`, `Identity` and `->` are basically all you need I think. It's a little bit of a shame they're spread out over so many packages.

**Comment by garyb** [comment]
Sure, sounds good to me. `purescript-functors` can pull in some of these scattered things, or we could deprecate them or something.

Identity and Const are special cases though perhaps?

**Comment by LiamGoodacre** [comment]
Is this dead?

**Comment by paf31** [comment]
Yes, and it's covered by `purescript-pairings` actually. Thanks!

**Pull request closed without merging**
